# Generated by Django 5.2.8 on 2026-05-02 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description complète')),
                ('what_to_bring', models.TextField(blank=True, verbose_name="Ce qu'il faut apporter")),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base (Fcfa)')),
                ('max_travelers', models.PositiveIntegerField(default=10, verbose_name='Nombre max de voyageurs')),
                ('duration_hours', models.FloatField(verbose_name='Durée (heures)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activité active')),
                ('cached_rating', models.FloatField(default=0.0, editable=False, verbose_name='Note moyenne (cache)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.city', verbose_name='Ville')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('categories', models.ManyToManyField(blank=True, related_name='activities', to='tour.category', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/%Y/%m/', verbose_name='Fichier image')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.activity', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('available_spots', models.PositiveIntegerField(verbose_name='Places disponibles')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour utiliser le prix de base', max_digits=10, null=True, verbose_name='Prix spécifique (€)')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tour.activity', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
                'ordering': ['date', 'start_time'],
                'unique_together': {('activity', 'date', 'start_time')},
            },
        ),
    ]
