# Generated by Django 5.2.8 on 2026-05-02 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('booking_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence de réservation')),
                ('number_of_travelers', models.PositiveIntegerField(default=1, verbose_name='Nombre de voyageurs')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total payé (€)')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('confirmed', 'Confirmée'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='Statut')),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.schedule', verbose_name='Créneau réservé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Voyageur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('method', models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('paypal', 'PayPal'), ('wire', 'Virement bancaire')], default='stripe', max_length=20, verbose_name='payment mode')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='ID of the transaction')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount payed in (FCFA)')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Payment suscceded')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking', verbose_name='reservation linked')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
