# Generated by Django 5.2.8 on 2026-05-02 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 étoile(s)'), (2, '2 étoile(s)'), (3, '3 étoile(s)'), (4, '4 étoile(s)'), (5, '5 étoile(s)')], verbose_name='Note')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name="Titre de l'avis")),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('is_visible', models.BooleanField(default=True, help_text="Décochez pour masquer l'avis (modération)", verbose_name='Avis visible')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tour.activity', verbose_name='Activité concernée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Voyageur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
